variable "resource_group_name" {
  type        = string
  description = "The name of an existing resource group to be imported."
}

variable "use_for_each" {
  type        = bool
  description = "Use `for_each` instead of `count` to create multiple resource instances."
  nullable    = false
}

variable "address_space" {
  type        = string
  default     = "10.0.0.0/16"
  description = "The address space that is used by the virtual network."
}

variable "address_spaces" {
  type        = list(string)
  default     = []
  description = "The list of the address spaces that is used by the virtual network."
}

# If no values specified, this defaults to Azure DNS 
variable "dns_servers" {
  type        = list(string)
  default     = []
  description = "The DNS servers to be used with vNet."
}

variable "location" {
  type        = string
  default     = null
  description = "The location/region where the virtual network is created. If provided, this will override resource_group_location. For backward compatibility."
}

variable "resource_group_location" {
  type        = string
  default     = null
  description = "The location/region where the virtual network is created. Changing this forces a new resource to be created."
}

variable "subnet_delegation" {
  type = map(list(object({
    name = string
    service_delegation = object({
      name    = string
      actions = optional(list(string))
    })
  })))
  default     = {}
  description = "`service_delegation` blocks for `azurerm_subnet` resource, subnet names as keys, list of delegation blocks as value, more details about delegation block could be found at the [document](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/subnet#delegation)."
  nullable    = false
}

variable "subnet_enforce_private_link_endpoint_network_policies" {
  type        = map(bool)
  default     = {}
  description = "A map with key (string) `subnet name`, value (bool) `true` or `false` to indicate enable or disable network policies for the private link endpoint on the subnet. Default value is false."
}

variable "subnet_names" {
  type        = list(string)
  default     = ["subnet1"]
  description = "A list of public subnets inside the vNet."
}

variable "subnet_prefixes" {
  type        = list(string)
  default     = ["10.0.1.0/24"]
  description = "The address prefix to use for the subnet."
}

variable "subnet_service_endpoints" {
  type        = map(list(string))
  default     = {}
  description = "A map with key (string) `subnet name`, value (list(string)) to indicate enabled service endpoints on the subnet. Default value is []."
}

variable "tags" {
  type = map(string)
  default = {
    environment = "dev"
  }
  description = "The tags to associate with your network and subnets."
}

# tflint-ignore: terraform_unused_declarations
variable "tracing_tags_enabled" {
  type        = bool
  default     = false
  description = "Whether enable tracing tags that generated by BridgeCrew Yor."
  nullable    = false
}

# tflint-ignore: terraform_unused_declarations
variable "tracing_tags_prefix" {
  type        = string
  default     = "avm_"
  description = "Default prefix for generated tracing tags"
  nullable    = false
}

variable "name" {
  type        = string
  default     = null
  description = "Name of the vnet to create. If provided, this will override vnet_name. For backward compatibility."
}

variable "vnet_name" {
  type        = string
  default     = "acctvnet"
  description = "Name of the vnet to create."
}

# NAT Gateway Configuration
variable "enable_nat_gateway" {
  type        = bool
  default     = false
  description = "Should a NAT Gateway be created for outbound internet access?"
  nullable    = false
}

variable "nat_gateway_subnet_names" {
  type        = list(string)
  default     = []
  description = "List of subnet names where NAT Gateway should be attached. NAT Gateway will be created for each subnet."
}

variable "nat_gateway_idle_timeout_in_minutes" {
  type        = number
  default     = 4
  description = "The idle timeout in minutes for the NAT Gateway. Defaults to 4."
}

variable "nat_gateway_name" {
  type        = string
  default     = null
  description = "Name of the NAT Gateway. If not provided, will be generated as '{vnet_name}-nat-{subnet_name}'."
}

# VPN Gateway Configuration
variable "enable_vpn_gateway" {
  type        = bool
  default     = false
  description = "Should a VPN Gateway be created?"
  nullable    = false
}

variable "gateway_subnet_cidr" {
  type        = string
  default     = null
  description = "CIDR block for the gateway subnet. Required if enable_vpn_gateway is true."
}

variable "vpn_gateway_sku" {
  type        = string
  default     = "VpnGw1"
  description = "The SKU of the VPN Gateway. Valid values are: VpnGw1, VpnGw2, VpnGw3, VpnGw1AZ, VpnGw2AZ, VpnGw3AZ."
}

variable "vpn_gateway_enable_bgp" {
  type        = bool
  default     = false
  description = "Should BGP be enabled on the VPN Gateway?"
  nullable    = false
}

variable "vpn_gateway_name" {
  type        = string
  default     = null
  description = "Name of the VPN Gateway. If not provided, will be generated as '{vnet_name}-vpn-gateway'."
}

variable "vpn_shared_key" {
  type        = string
  default     = null
  sensitive   = true
  description = "The shared key for the VPN connection. Required if enable_vpn_gateway is true."
}

variable "remote_gateway_ip" {
  type        = string
  default     = null
  description = "The public IP address of the remote gateway. Required if enable_vpn_gateway is true."
}

variable "remote_address_spaces" {
  type        = list(string)
  default     = []
  description = "The address spaces of the remote network. Required if enable_vpn_gateway is true."
}

variable "remote_gateway_name" {
  type        = string
  default     = null
  description = "Name of the Local Network Gateway (remote gateway). If not provided, will be generated as '{vnet_name}-remote-gateway'."
}

variable "vpn_connection_name" {
  type        = string
  default     = null
  description = "Name of the VPN connection. If not provided, will be generated as '{vnet_name}-vpn-connection'."
}

# Network Security Group Configuration
variable "enable_internal_nsg" {
  type        = bool
  default     = false
  description = "Should an internal Network Security Group be created and associated with subnets?"
  nullable    = false
}

variable "internal_nsg_name" {
  type        = string
  default     = "internal"
  description = "Name of the internal Network Security Group."
}

variable "internal_nsg_source_address_prefix" {
  type        = list(string)
  default     = []
  description = "List of source address prefixes allowed in the NSG rules. If empty, will default to the vNet address space."
}
